;this file for FamiTone2 library generated by text2data tool
FT_DPCM_PTR=$c000
.export _bloboo_music_data
_bloboo_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env5,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$04,$0a	;1
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;2
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;25
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;26
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;27
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;28
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;29
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;30
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;31
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;32
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;33
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;34
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;35
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;37
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $cf,$cf,$cc,$c9,$c7,$c5,$c3,$c3,$c2,$03,$c1,$02,$c0,$00,$0c
@env3:
	.byte $cc,$05,$cb,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c6,$c5,$c4,$c4,$c3,$c2
	.byte $c1,$c0,$00,$11
@env4:
	.byte $c8,$00,$00
@env5:
	.byte $c0,$c6,$ca,$c9,$ca,$00,$04


@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $00,$f9,$83
@ref1:
	.byte $00,$f9,$83
@ref2:
	.byte $00,$8d,$80,$38,$3a,$8b,$32,$97,$3a,$3c,$8d,$3a,$8d,$33,$36,$89
	.byte $3b,$36,$89,$32,$81
@ref3:
	.byte $00,$8d,$38,$3a,$8b,$32,$95,$28,$c5
@ref4:
	.byte $00,$8d,$38,$3a,$8b,$32,$97,$3a,$3c,$8d,$3a,$8d,$33,$36,$89,$3b
	.byte $36,$89,$32,$00
@ref5:
	.byte $32,$8b,$00,$32,$8b,$00,$32,$8b,$00,$32,$89,$36,$00,$36,$8b,$00
	.byte $36,$8b,$00,$3a,$87,$00,$36,$00,$32,$87,$00,$28,$81
@ref6:
	.byte $00,$8d,$38,$3a,$8b,$32,$97,$3a,$3c,$8d,$3a,$8d,$33,$36,$89,$3b
	.byte $36,$89,$32,$81
	.byte $ff,$09
	.word @ref3
	.byte $ff,$14
	.word @ref4
	.byte $ff,$1d
	.word @ref5
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref10:
	.byte $00,$f9,$83
@ref11:
	.byte $00,$f9,$83
@ref12:
	.byte $00,$95,$86,$38,$3a,$8b,$32,$97,$3a,$3c,$8d,$3a,$8d,$33,$36,$89
	.byte $3b,$36,$85
@ref13:
	.byte $32,$85,$00,$8d,$38,$3a,$8b,$32,$95,$28,$bd
@ref14:
	.byte $00,$95,$38,$3a,$8b,$32,$97,$3a,$3c,$8d,$3a,$8d,$33,$36,$89,$3b
	.byte $36,$85
@ref15:
	.byte $83,$32,$00,$32,$8b,$00,$32,$8b,$00,$32,$8b,$00,$32,$89,$36,$00
	.byte $36,$8b,$00,$36,$8b,$00,$3a,$87,$00,$36,$00,$32,$85
	.byte $ff,$12
	.word @ref14
	.byte $ff,$0b
	.word @ref13
	.byte $ff,$12
	.word @ref14
	.byte $ff,$1d
	.word @ref15
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref20:
	.byte $80,$32,$8b,$00,$32,$8b,$00,$3a,$8b,$00,$3a,$8b,$00,$3c,$8b,$00
	.byte $3c,$87,$00,$41,$00,$85,$29,$00,$40,$8b,$28,$81
@ref21:
	.byte $32,$8b,$00,$32,$8b,$00,$3a,$8b,$00,$3a,$8b,$00,$3c,$8b,$00,$3c
	.byte $87,$00,$41,$00,$85,$29,$00,$40,$8b,$28,$81
	.byte $ff,$1b
	.word @ref21
	.byte $ff,$1b
	.word @ref21
	.byte $ff,$1b
	.word @ref21
@ref25:
	.byte $2c,$8b,$00,$2c,$87,$00,$2c,$00,$24,$8b,$00,$24,$87,$00,$24,$00
	.byte $28,$8b,$00,$28,$87,$00,$28,$00,$28,$8b,$00,$28,$87,$00,$28,$81
	.byte $ff,$1b
	.word @ref21
	.byte $ff,$1b
	.word @ref21
	.byte $ff,$1b
	.word @ref21
	.byte $ff,$20
	.word @ref25
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref30:
	.byte $84,$16,$8d,$82,$02,$89,$84,$16,$00,$16,$8d,$82,$02,$89,$84,$16
	.byte $00,$16,$8d,$82,$02,$89,$84,$16,$00,$16,$89,$16,$00,$82,$02,$89
	.byte $84,$16,$00
@ref31:
	.byte $16,$8d,$82,$02,$89,$84,$16,$00,$16,$8d,$82,$02,$89,$84,$16,$00
	.byte $16,$8d,$82,$02,$89,$84,$16,$00,$16,$89,$16,$00,$82,$02,$89,$84
	.byte $16,$00
	.byte $ff,$1a
	.word @ref31
	.byte $ff,$1a
	.word @ref31
	.byte $ff,$1a
	.word @ref31
	.byte $ff,$1a
	.word @ref31
	.byte $ff,$1a
	.word @ref31
	.byte $ff,$1a
	.word @ref31
	.byte $ff,$1a
	.word @ref31
	.byte $ff,$1a
	.word @ref31
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref40:
	.byte $02,$8d,$02,$89,$03,$02,$89,$03,$02,$89,$03,$02,$8d,$02,$89,$03
	.byte $02,$89,$03,$02,$89,$02,$81
	.byte $ff,$17
	.word @ref40
	.byte $ff,$17
	.word @ref40
	.byte $ff,$17
	.word @ref40
	.byte $ff,$17
	.word @ref40
	.byte $ff,$17
	.word @ref40
	.byte $ff,$17
	.word @ref40
	.byte $ff,$17
	.word @ref40
	.byte $ff,$17
	.word @ref40
	.byte $ff,$17
	.word @ref40
	.byte $fd
	.word @song0ch4loop
